version: "3.8"

name: useful-services

services:
  # AFFiNE
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    networks:
      - caddy
    ports:
      - '${AFFINE_PORT:-3010}:3010'
    expose:
      - '4000'
    depends_on:
      affine_redis:
        condition: service_healthy
      affine_postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${AFFINE_UPLOAD_LOCATION}:/root/.affine/storage
      - ${AFFINE_CONFIG_LOCATION}:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=affine_redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USERNAME}:${AFFINE_DB_PASSWORD}@affine_postgres:5432/${AFFINE_DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    networks:
      - caddy
    volumes:
      # custom configurations
      - ${AFFINE_UPLOAD_LOCATION}:/root/.affine/storage
      - ${AFFINE_CONFIG_LOCATION}:/root/.affine/config
    command: [ 'sh', '-c', 'node ./scripts/self-host-predeploy.js' ]
    environment:
      - REDIS_SERVER_HOST=affine_redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USERNAME}:${AFFINE_DB_PASSWORD}@postgres:5432/${AFFINE_DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      affine_postgres:
        condition: service_healthy
      affine_redis:
        condition: service_healthy

  affine_redis:
    image: redis
    container_name: affine_redis
    networks:
      - caddy
    healthcheck:
      test: [ 'CMD', 'redis-cli', '--raw', 'incr', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  affine_postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    networks:
      - caddy
    volumes:
      - ${AFFINE_DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AFFINE_DB_USERNAME}
      POSTGRES_PASSWORD: ${AFFINE_DB_PASSWORD}
      POSTGRES_DB: ${AFFINE_DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test:
        [ 'CMD', 'pg_isready', '-U', "${AFFINE_DB_USERNAME}", '-d', "${AFFINE_DB_DATABASE:-affine}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # GitLab
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: ${GITLAB_HOSTNAME}
    restart: always
    networks:
      - caddy
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #####################################
        #########Basic configuration#########
        #####################################
        external_url '${GITLAB_EXTERNAL_URL}'
        nginx['enable'] = ${GITLAB_NGINX_ENABLE}
        letsencrypt['enable'] = ${GITLAB_LETSENCRYPT_ENABLE}
        
        # DO NOT EDIT THE NEXT 3 LINES WITHOUT SYNCING IT WITH `Caddyfile`
        gitlab_rails['trusted_proxies'] = ['caddy']
        gitlab_workhorse['listen_network'] = 'tcp'
        gitlab_workhorse['listen_addr'] = '0.0.0.0:8000'
        
        ####################################
        #########SMTP configuration#########
        ####################################
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = '${GITLAB_SMTP_AUTHENTICATION}'
        gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_SMTP_ENABLE_STARTTLS_AUTO}
        gitlab_rails['smtp_tls'] = ${GITLAB_SMTP_TLS}
        gitlab_rails['gitlab_email_from'] = '${GITLAB_EMAIL_FROM}'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab -  Example Name'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_EMAIL_REPLY_TO}'

        #####################################
        ##Personal Access Tokens Expiration##
        #####################################
        gitlab_rails['personal_access_token_expiration_enforced'] = true
        gitlab_rails['personal_access_token_expiration'] = ${GITLAB_PERSONAL_ACCESS_TOKEN_EXPIRATION}
        gitlab_rails['access_token_expiration_enforced'] = true
        gitlab_rails['access_token_expiration'] = ${GITLAB_ACCESS_TOKEN_EXPIRATION}

        ####################################
        #########Session expiration#########
        ####################################
        gitlab_rails['session_expire_delay'] = ${GITLAB_SESSION_EXPIRE_DELAY}
    ports:
      - '2222:22'
    expose:
      - '8000'
    volumes:
      - ${GITLAB_CONFIG_LOCATION}:/etc/gitlab
      - ${GITLAB_LOGS_LOCATION}:/var/log/gitlab
      - ${GITLAB_DATA_LOCATION}:/var/opt/gitlab
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g

  #Immich
  immich-server:
    container_name: immich_server
    networks:
      - caddy
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    expose:
      - '6781'
    depends_on:
      - immich-redis
      - immich_database
    restart: always

  immich-redis:
    container_name: immich_redis
    networks:
      - caddy
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich_database:
    container_name: immich_postgres
    networks:
      - caddy
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:5f6a838e4e44c8e0e019d0ebfe3ee8952b69afc2809b2c25f7b0119641978e91
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${IMMICH_DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

  # WireGuard
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    networks:
      - caddy
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
    ports:
      - '51820:51820/udp'
    expose:
      - '51821'
    volumes:
      - ${WG_CONFIG_LOCATION}:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped

  # Caddy
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/certs:/certs

networks:
  caddy:
    driver: bridge
